on:
  push:
    paths: "lesson03/*.py"
    branches:
      - main
  workflow_dispatch:

jobs:
  # code check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python(3.12)
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: code check in lesson02
        run: |
          cd lesson03
          python test_01.py

      - name: code check in lesson02(is_int_list)
        if: always()
        run: |
          cd lesson03
          python test_02.py
