on:
  push:
    paths: "lesson01/*.py"
    branches:
      - main

jobs:
  # code check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python(3.12)
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install black formatter
        run: pip install black

      # コードをフォーマットするが、結果は別の場所に保存する
      - name: check formatting
        run: black lesson01/ --check --diff
